In [1]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("C:/Users/Ujjal Mondal/Downloads/Sample - Superstore.csv/Sample - Superstore.csv")

In [9]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06-12-2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [10]:
df.shape

(9994, 21)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [14]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [22]:
df["Order Date"] = pd.to_datetime(df["Order Date"], format="mixed")
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="mixed")

In [25]:
df["Order Year"] = df["Order Date"].dt.year
df["Order Month"] = df["Order Date"].dt.month
df["Order Month Name"] = df["Order Date"].dt.month_name()
df["Order Quarter"] = df["Order Date"].dt.quarter

In [26]:
df.dtypes

Row ID                       int64
Order ID                    object
Order Date          datetime64[ns]
Ship Date           datetime64[ns]
Ship Mode                   object
Customer ID                 object
Customer Name               object
Segment                     object
Country                     object
City                        object
State                       object
Postal Code                  int64
Region                      object
Product ID                  object
Category                    object
Sub-Category                object
Product Name                object
Sales                      float64
Quantity                     int64
Discount                   float64
Profit                     float64
Order Year                   int32
Order Month                  int32
Order Month Name            object
Order Quarter                int32
dtype: object

### KPI Calculation

In [36]:
total_sales = df["Sales"].sum()
total_profit = df["Profit"].sum()
total_orders = df["Order ID"].nunique()
avg_order_value = total_sales / total_orders 
profit_margin = (total_profit / total_sales) * 100

print("Total Sales:", total_sales)
print("Total Profit:", total_profit)
print("Total Orders:", total_orders)
print("Avg Order Value:",  avg_order_value)
print("Profit Margin:", profit_margin)

Total Sales: 2297200.8603
Total Profit: 286397.0217
Total Orders: 5009
Avg Order Value: 458.6146656618087
Profit Margin: 12.467217240315605

### Category Analysis

In [32]:
df.groupby("Category")["Sales"].sum().sort_values(ascending = False)

Category
Technology         836154.0330
Furniture          741999.7953
Office Supplies    719047.0320
Name: Sales, dtype: float64

In [33]:
df.groupby("Category")["Profit"].sum().sort_values(ascending = False)

Category
Technology         145454.9481
Office Supplies    122490.8008
Furniture           18451.2728
Name: Profit, dtype: float64

### Sub-Category Analysis

In [34]:
df.groupby("Sub-Category")["Sales"].sum().sort_values(ascending = False).head(10)

Sub-Category
Phones         330007.0540
Chairs         328449.1030
Storage        223843.6080
Tables         206965.5320
Binders        203412.7330
Machines       189238.6310
Accessories    167380.3180
Copiers        149528.0300
Bookcases      114879.9963
Appliances     107532.1610
Name: Sales, dtype: float64

In [35]:
df.groupby("Sub-Category")["Profit"].sum().sort_values(ascending = False).head(10)

Sub-Category
Copiers        55617.8249
Phones         44515.7306
Accessories    41936.6357
Paper          34053.5693
Binders        30221.7633
Chairs         26590.1663
Storage        21278.8264
Appliances     18138.0054
Furnishings    13059.1436
Envelopes       6964.1767
Name: Profit, dtype: float64

### Region Analysis

In [38]:
df.groupby("Region")[["Sales","Profit"]].sum().sort_values("Sales", ascending = False)

               Sales       Profit
Region
West     725457.8245  108418.4489
East     678781.2400   91522.7800
Central  501239.8908   39706.3625
South    391721.9050   46749.4303

### State Analysis

In [43]:
df.groupby("State")[["Sales","Profit"]].sum().sort_values("Sales", ascending = False).head(10)

                    Sales      Profit
State
California    457687.6315  76381.3871
New York      310876.2710  74038.5486
Texas         170188.0458 -25729.3563
Washington    138641.2700  33402.6517
Pennsylvania  116511.9140 -15559.9603
Florida        89473.7080  -3399.3017
Illinois       80166.1010 -12607.8870
Ohio           78258.1360 -16971.3766
Michigan       76269.6140  24463.1876
Virginia       70636.7200  18597.9504

### Profitability by State

In [41]:
df.groupby("State")[["Sales","Profit"]].sum().sort_values("Profit",ascending = False).head(10)

                  Sales      Profit
State
California  457687.6315  76381.3871
New York    310876.2710  74038.5486
Washington  138641.2700  33402.6517
Michigan     76269.6140  24463.1876
Virginia     70636.7200  18597.9504
Indiana      53555.3600  18382.9363
Georgia      49095.8400  16250.0433
Kentucky     36591.7500  11199.6966
Minnesota    29863.1500  10823.1874
Delaware     27451.0690   9977.3748

In [42]:
df[["Sales","Profit","Discount"]].corr()

             Sales    Profit  Discount
Sales     1.000000  0.479064 -0.028190
Profit    0.479064  1.000000 -0.219487
Discount -0.028190 -0.219487  1.000000

In [44]:
df.groupby("Segment")[["Sales","Profit"]].sum()

                    Sales       Profit
Segment
Consumer     1.161401e+06  134119.2092
Corporate    7.061464e+05   91979.1340
Home Office  4.296531e+05   60298.6785

In [47]:
df.groupby("Ship Mode")[["Sales","Profit"]].sum()

                       Sales       Profit
Ship Mode
First Class     3.514284e+05   48969.8399
Same Day        1.283631e+05   15891.7589
Second Class    4.591936e+05   57446.6354
Standard Class  1.358216e+06  164088.7875

In [48]:
df.groupby("Sub-Category")[["Profit"]].sum().sort_values("Profit")

                  Profit
Sub-Category
Tables       -17725.4811
Bookcases     -3472.5560
Supplies      -1189.0995
Fasteners       949.5182
Machines       3384.7569
Labels         5546.2540
Art            6527.7870
Envelopes      6964.1767
Furnishings   13059.1436
Appliances    18138.0054
Storage       21278.8264
Chairs        26590.1663
Binders       30221.7633
Paper         34053.5693
Accessories   41936.6357
Phones        44515.7306
Copiers       55617.8249

In [51]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("-", "_")
)

df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub_category',
       'product_name', 'sales', 'quantity', 'discount', 'profit', 'order_year',
       'order_month', 'order_month_name', 'order_quarter'],
      dtype='object')

In [54]:
df.to_csv("superstore_clean.csv", index= False)

In [55]:
pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\ujjal mondal\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: psycopg2-binary in c:\users\ujjal mondal\anaconda3\lib\site-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in c:\users\ujjal mondal\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ujjal mondal\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [60]:
from sqlalchemy import create_engine

# step 1: conncet to postgreSQL
# Replace placeholders with your actual details
username = "postgres"      #default user
password = "767977" 
host  = "localhost"
port = "5432"
database = "Super_store"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

#step 2 : load data frame into postgreSQL
table_name = "superstore"
df.to_sql(table_name, engine, if_exists = "replace", index=False)

print(f"Data succesddfully loaded into table '{table_name}' in database '{database}'.")

Data succesddfully loaded into table 'superstore' in database 'Super_store'.